const SHORT_MOVIE_DURATION = 40;

const SCREEN_SIZE = {
  M: 768,
  L: 1280,
};

const MOVIES_AMOUNT = {
  S: 5,
  M: 8,
  L: 16,
};

const ADDED_MOVIES_AMOUNT = {
  S: 1,
  M: 2,
  L: 4,
};

const SCREEN_1150 = 1150;
const SCREEN_800 = 800;
const SCREEN_650 = 650;

const MOVIES_16 = 16;
const MOVIES_12 = 12;
const MOVIES_8 = 8;
const MOVIES_5 = 5;

const MOVIES_4_ADD = 4;
const MOVIES_3_ADD = 3;
const MOVIES_2_ADD = 2;

const SHORT_FILM_DURATION = 40;

const RESIZE_DELAY = 300;

export {
  SHORT_MOVIE_DURATION,
  SCREEN_SIZE,
  MOVIES_AMOUNT,
    SCREEN_1150,
    SCREEN_800,
    SCREEN_650,
    MOVIES_16 ,
    ADDED_MOVIES_AMOUNT,
    MOVIES_12,
    MOVIES_8,
    MOVIES_5,
    MOVIES_4_ADD,
    MOVIES_3_ADD,
    MOVIES_2_ADD,
    SHORT_FILM_DURATION,
    RESIZE_DELAY,
}